#!/usr/bin/env python3
"""Generate XOR-encrypted C++ byte arrays for the copyright protection layer."""

XOR_KEY = 0xA7

strings = {
    "kApiKey": "PalDiscordPlugin b75c2541e6eb17db69d6cf441827e19b91c13a7444eb39e89e9b7dc635b4c717",
    "kApiKeyPrefix": "PalDiscordPlugin",
    "kCopyright": "PalDiscordPlugin\nCopyright 2026 RL-Dev.de",
    "kNonCommercial": "PalDiscordPlugin [NON-COMMERCIAL VERSION] - Free for personal/community servers only. Commercial use is prohibited.",
    "kProductName": "PalDiscordPlugin",
}

print("// Auto-generated by tools/gen_crypto.py - DO NOT EDIT")
print()
for name, text in strings.items():
    enc = [ord(c) ^ XOR_KEY for c in text]
    bytes_str = ", ".join(f"0x{b:02x}" for b in enc)
    print(f"const std::vector<unsigned char> CopyrightCrypto::{name} = {{ {bytes_str} }};")
